### ISSUE TITLE
UI Tasks - Admin User Story 2 - Publish and Modify Catalog Items - Parent Issue #7

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#103]
- [ ] 1. Add UI component to the Axure site, including ability to view results
- [ ] 2. Peer review by @lnajera, @lutech , @ClaireReinken 
- [x]  3. [UI] Implement UI Behavior with sample data

**Comment by jennymnh** [comment]
These questions were originally added to the parent issue #14, reposting them here as well:

> What would go under the categories dropdown?
> Software, Hardware, and Services? Or do we want to list every type of hardware/service (standard desktops/power desktops/value added services/etc)?
> 
> Also, is there any reason (maybe it's a typo?) that many of these items are sub items on the list?
> ![image](https://cloud.githubusercontent.com/assets/9370407/23098048/2807315e-f612-11e6-9ba4-fc4774c4758c.png)
> 
> 
> Another question, is searching implied? How would an admin know which items are available to modify?
> 
> If a search page is implied, which filter fields would show up on the search page?

@tzhangfei

**Comment by jennymnh** [comment]
Should there be an individual page for each product? If so, should all of this information be seen on it?

Example workflow:

1. Search for products
2. See a table of results
3. Be able to view details of each product item
4. On individual product item page, be able to edit/delete

**Comment by ClaireReinken** [comment]
These questions were originally added to the parent issue #14, reposting them here as well:


What would go under the categories dropdown? 
 Software, Hardware, and Services? Or do we want to list every type of hardware/service (standard desktops/power desktops/value added services/etc)? - All types listed in the category column of the data set. We need to add "product type" to the acceptance criteria (I'll update it) so include hardware, services, and software.

Also, is there any reason (maybe it's a typo?) that many of these items are sub items on the list? - No, it's just because GitHub does not show bullets well and the acceptance criteria was originally copied from Word and then updated in GitHub. 
image

Another question, is searching implied? How would an admin know which items are available to modify? - Yes, they need to be able to search items already added to the catalog

If a search page is implied, which filter fields would show up on the search page? The admin should be able to search by one or a combination of the columns in the data set

**Comment by ClaireReinken** [comment]
Should there be an individual page for each product? If so, should all of this information be seen on it?

Example workflow:
1.Search for products
2.See a table of results
3.Be able to view details of each product item
4.On individual product item page, be able to edit/delete

Yes

**Comment by llin-freeman** [comment]
I'll add the "expiration date" column to the dataset.
