### ISSUE TITLE
UI Tasks - Admin User Story 4 - Delete Products and Services from Catalog - Parent Issue #115

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#105]
- [ ] 1. Add UI component to the Axure site, including ability to view results
- [ ] 2. Peer review by @lnajera, @lutech , @ClaireReinken 
- [ ]  3. [UI] Implement UI Behavior with sample data
