### ISSUE TITLE
UI Tasks - Admin User Story 9 - View Overall Order Statistics - Parent Issue #14

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#107]
- [ ] 1. Add UI component to the Axure site, including ability to view results
- [ ] 2. Peer review by @lnajera, @lutech , @ClaireReinken 
- [ ]  3. [UI] Implement UI Behavior with sample data

**Comment by jennymnh** [comment]
Copied from parent issue

> After I search by these filters (the acceptance criterias), what other type of information would show? I would need to know what types of fields go into an order/expenditure report so I could mock it up.

**Comment by ClaireReinken** [comment]
After I search by these filters (the acceptance criteria's), what other type of information would show? I would need to know what types of fields go into an order/expenditure report so I could mock it up. - The Q&As indicated that the reports could consist of the following: Examples include, but are not limited to, the following: total expenditures by quarter and fiscal year, expenditures by category over a period of time, expenditures by vendor, license/product counts by vendor, etc. And: Examples of visualizations include, but are not limited to, the following: trends in orders by contract, trends in orders by department, trends in orders by product number, gross expenditures by contract, etc.

**Comment by jennymnh** [comment]
Thank you. Another question -
The acceptance criteria lists "Product" as

•	View orders by product (specific product number)
•	View expenditures by product (specific product number)

What is this number? the SKU? OEM? (ironically these numbers are both the same)

And if they are, I propose we revise this to say "View orders/expenditures by SKU/OEM"

**Comment by ClaireReinken** [comment]
Let's discuss in today's meeting. I have a slightly more detailed idea on how the reports should look.
