### ISSUE TITLE
UI Tasks - Authorized User Story 1 - Quick Search - Parent Issue #16

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#81]
- [x] 1. [UX] Add UI component to the Axure site, including ability to view results
- [x] 2. [UX] Peer review by @lnajera, @lutech , @ClaireReinken 
- [x]  3. [UI] Implement UI Behavior with sample data
