### ISSUE TITLE
UI Tasks - Authorized User Story 2 - Advanced Search - Parent Issue # 17

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#83]
- [x] 1. Add UI component to the Axure site
- [x] 2. Peer review by @lnajera, @lutech , @ClaireReinken 
- [ ]  3. [UI] Implement UI Behavior with sample data

**Comment by ClaireReinken** [comment]
Re-opening for QA

**Comment by ClaireReinken** [comment]
Closing. The parent card will be moved to QC doing on the board.
