### ISSUE TITLE
UI Tasks - Authorized User Story 3 - Browse Inventory by Category - Parent Issue #18

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#85]
- [x] 1. Add UI component to the Axure site
- [x] 2. Peer review by @lnajera, @lutech , @ClaireReinken 
- [x]  3. Add all pages as place holder for future dev work.
- [x]  4. [UI] Implement UI Behavior with sample data
