### ISSUE TITLE
UI Tasks - Authorized User Story 6 - Browse Item Details - Parent Issue #21

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#91]
- [x] 1. Add UI component to the Axure site, including ability to view results
- [x] 2. Peer review by @lnajera, @lutech , @ClaireReinken 
- [x]  3. [UI] Implement UI Behavior with sample data

**Comment by ClaireReinken** [comment]
Reopening for QC

**Comment by ClaireReinken** [comment]
Only the parent card will move to QC Doing on the board. Closing.
